export PATH="$PATH:/home/oxhart/scripts/bin/"
export PATH="$PATH:/home/oxhart/.local/bin/"
export PATH="$PATH:/home/oxhart/.local/jdtls/bin/"
export PATH="$HOME/.nodenv/bin:$PATH"
. "$HOME/.cargo/env"
