#!/bin/bash
#
#script to init few things in awesomeWM

function run {
  if [[ "$1" == "sudo" ]]; then
    test="$2"
  else
    test="$1"
  fi

  if ! pgrep -f "$test"; then
    "$@"
    echo "$test"
  fi
}

function initialize {
  if ! pgrep -f "picom"; then
    "$@"
  fi
}

function start_bluetooth {
  if ! pgrep -f "bluetooth"; then
    "$@"
  fi
}

function start_dhcpcd {
  if ! pgref -f "dhcpcd"; then
    "$@"
  fi
}

#nvidia-settings --assign CurrentMetaMode="DP-0: 2560x1600+0+0 { ForceFullCompositionPipeline = On }"
initialize nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"
initialize setxkbmap -layout us -variant altgr-intl -option nodeadkeys
initialize picom --fade-in-step=1 --fade-out-step=1 --fade-delta=0 --inactive-opacity=1 &
#initialize sudo rfkill unblock wifi
#initialize sudo wpa_supplicant -B -i wlp8s0 -c /etc/wpa_supplicant/hiden.conf
#initialize sudo dhcpcd wlp8s0
start_bluetooth sudo systemctl start bluetooth
#initialize bluetoothctl
