#!/usr/bin/python

import math
import sys
import re

args = sys.argv
if not re.search(r"\d|math", args[1]) :
    print("wrong usage")
    exit()

if (len(args) == 2) :
    print(eval(args[1]))
else:
    print('the argument should be in this form: "5*5"')

